#ifndef arduinocommands_h
#define arduinocommands_h

//Incoming commands
#define ARDUCOMMAND_PING_REQUEST 100
#define ARDUCOMMAND_HOLD 102
#define ARDUCOMMAND_SET_TIME 105
#define ARDUCOMMAND_GET_TIME_REQUEST 106
#define ARDUCOMMAND_BEEP 108

//Outcoming commands
#define ARDUCOMMAND_PING_RESPONSE 101
#define ARDUCOMMAND_COMMAND_FAILED 103
#define ARDUCOMMAND_SHUTDOWN_SIGNAL 104
#define ARDUCOMMAND_GET_TIME_RESPONSE 107
#define ARDUCOMMAND_CONFIRMATION 109

#endif