//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://weather.yandex.ru/forecast", IsNullable=true)]
public partial class station {
    
    private string langField;
    
    private string distanceField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string distance {
        get {
            return this.distanceField;
        }
        set {
            this.distanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://weather.yandex.ru/forecast", IsNullable=true)]
public partial class temperature {
    
    private string colorField;
    
    private string plateField;
    
    private string typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string plate {
        get {
            return this.plateField;
        }
        set {
            this.plateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://weather.yandex.ru/forecast", IsNullable=false)]
public partial class weather_condition {
    
    private string codeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://weather.yandex.ru/forecast", IsNullable=true)]
public partial class image {
    
    private string typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
[System.Xml.Serialization.XmlRootAttribute("image-v2", Namespace="http://weather.yandex.ru/forecast", IsNullable=true)]
public partial class imagev2 {
    
    private string colorField;
    
    private string typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
[System.Xml.Serialization.XmlRootAttribute("image-v3", Namespace="http://weather.yandex.ru/forecast", IsNullable=true)]
public partial class imagev3 {
    
    private string typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://weather.yandex.ru/forecast", IsNullable=true)]
public partial class pressure {
    
    private string unitsField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://weather.yandex.ru/forecast", IsNullable=true)]
public partial class mslp_pressure {
    
    private string unitsField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://weather.yandex.ru/forecast", IsNullable=true)]
public partial class season {
    
    private string typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://weather.yandex.ru/forecast", IsNullable=false)]
public partial class forecast {
    
    private forecastFact[] factField;
    
    private forecastYesterday[] yesterdayField;
    
    private temperature[] informerField;
    
    private forecastDay[] dayField;
    
    private string country_idField;
    
    private string partField;
    
    private string linkField;
    
    private string part_idField;
    
    private string latField;
    
    private string slugField;
    
    private string cityField;
    
    private string climateField;
    
    private string countryField;
    
    private string regionField;
    
    private string lonField;
    
    private string zoomField;
    
    private string idField;
    
    private string sourceField;
    
    private string exactnameField;
    
    private string geoidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("fact")]
    public forecastFact[] fact {
        get {
            return this.factField;
        }
        set {
            this.factField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("yesterday")]
    public forecastYesterday[] yesterday {
        get {
            return this.yesterdayField;
        }
        set {
            this.yesterdayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("temperature", typeof(temperature))]
    public temperature[] informer {
        get {
            return this.informerField;
        }
        set {
            this.informerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("day")]
    public forecastDay[] day {
        get {
            return this.dayField;
        }
        set {
            this.dayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string country_id {
        get {
            return this.country_idField;
        }
        set {
            this.country_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string part {
        get {
            return this.partField;
        }
        set {
            this.partField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string link {
        get {
            return this.linkField;
        }
        set {
            this.linkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string part_id {
        get {
            return this.part_idField;
        }
        set {
            this.part_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lat {
        get {
            return this.latField;
        }
        set {
            this.latField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string slug {
        get {
            return this.slugField;
        }
        set {
            this.slugField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string climate {
        get {
            return this.climateField;
        }
        set {
            this.climateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string region {
        get {
            return this.regionField;
        }
        set {
            this.regionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lon {
        get {
            return this.lonField;
        }
        set {
            this.lonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string zoom {
        get {
            return this.zoomField;
        }
        set {
            this.zoomField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string exactname {
        get {
            return this.exactnameField;
        }
        set {
            this.exactnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string geoid {
        get {
            return this.geoidField;
        }
        set {
            this.geoidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
public partial class forecastFact {
    
    private string observation_timeField;
    
    private string uptimeField;
    
    private string weather_typeField;
    
    private string weather_type_shortField;
    
    private string weather_type_ttField;
    
    private string weather_type_short_ttField;
    
    private string weather_type_trField;
    
    private string weather_type_short_trField;
    
    private string weather_type_kzField;
    
    private string weather_type_short_kzField;
    
    private string weather_type_uaField;
    
    private string weather_type_short_uaField;
    
    private string weather_type_byField;
    
    private string weather_type_short_byField;
    
    private string wind_directionField;
    
    private string wind_speedField;
    
    private string humidityField;
    
    private string daytimeField;
    
    private string ipad_imageField;
    
    private station[] stationField;
    
    private temperature temperatureField;
    
    private weather_condition[] weather_conditionField;
    
    private image[] imageField;
    
    private imagev2[] imagev2Field;
    
    private imagev3[] imagev3Field;
    
    private pressure[] pressureField;
    
    private mslp_pressure[] mslp_pressureField;
    
    private season[] seasonField;
    
    /// <remarks/>
    public string observation_time {
        get {
            return this.observation_timeField;
        }
        set {
            this.observation_timeField = value;
        }
    }
    
    /// <remarks/>
    public string uptime {
        get {
            return this.uptimeField;
        }
        set {
            this.uptimeField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type {
        get {
            return this.weather_typeField;
        }
        set {
            this.weather_typeField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_short {
        get {
            return this.weather_type_shortField;
        }
        set {
            this.weather_type_shortField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_tt {
        get {
            return this.weather_type_ttField;
        }
        set {
            this.weather_type_ttField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_short_tt {
        get {
            return this.weather_type_short_ttField;
        }
        set {
            this.weather_type_short_ttField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_tr {
        get {
            return this.weather_type_trField;
        }
        set {
            this.weather_type_trField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_short_tr {
        get {
            return this.weather_type_short_trField;
        }
        set {
            this.weather_type_short_trField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_kz {
        get {
            return this.weather_type_kzField;
        }
        set {
            this.weather_type_kzField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_short_kz {
        get {
            return this.weather_type_short_kzField;
        }
        set {
            this.weather_type_short_kzField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_ua {
        get {
            return this.weather_type_uaField;
        }
        set {
            this.weather_type_uaField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_short_ua {
        get {
            return this.weather_type_short_uaField;
        }
        set {
            this.weather_type_short_uaField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_by {
        get {
            return this.weather_type_byField;
        }
        set {
            this.weather_type_byField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_short_by {
        get {
            return this.weather_type_short_byField;
        }
        set {
            this.weather_type_short_byField = value;
        }
    }
    
    /// <remarks/>
    public string wind_direction {
        get {
            return this.wind_directionField;
        }
        set {
            this.wind_directionField = value;
        }
    }
    
    /// <remarks/>
    public string wind_speed {
        get {
            return this.wind_speedField;
        }
        set {
            this.wind_speedField = value;
        }
    }
    
    /// <remarks/>
    public string humidity {
        get {
            return this.humidityField;
        }
        set {
            this.humidityField = value;
        }
    }
    
    /// <remarks/>
    public string daytime {
        get {
            return this.daytimeField;
        }
        set {
            this.daytimeField = value;
        }
    }
    
    /// <remarks/>
    public string ipad_image {
        get {
            return this.ipad_imageField;
        }
        set {
            this.ipad_imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("station", IsNullable=true)]
    public station[] station {
        get {
            return this.stationField;
        }
        set {
            this.stationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("temperature", IsNullable=true)]
    public temperature temperature {
        get {
            return this.temperatureField;
        }
        set {
            this.temperatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("weather_condition")]
    public weather_condition[] weather_condition {
        get {
            return this.weather_conditionField;
        }
        set {
            this.weather_conditionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("image", IsNullable=true)]
    public image[] image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("image-v2", IsNullable=true)]
    public imagev2[] imagev2 {
        get {
            return this.imagev2Field;
        }
        set {
            this.imagev2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("image-v3", IsNullable=true)]
    public imagev3[] imagev3 {
        get {
            return this.imagev3Field;
        }
        set {
            this.imagev3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pressure", IsNullable=true)]
    public pressure[] pressure {
        get {
            return this.pressureField;
        }
        set {
            this.pressureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mslp_pressure", IsNullable=true)]
    public mslp_pressure[] mslp_pressure {
        get {
            return this.mslp_pressureField;
        }
        set {
            this.mslp_pressureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("season", IsNullable=true)]
    public season[] season {
        get {
            return this.seasonField;
        }
        set {
            this.seasonField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
public partial class forecastYesterday {
    
    private string observation_timeField;
    
    private string uptimeField;
    
    private string weather_typeField;
    
    private string weather_type_shortField;
    
    private string weather_type_ttField;
    
    private string weather_type_short_ttField;
    
    private string weather_type_trField;
    
    private string weather_type_short_trField;
    
    private string weather_type_kzField;
    
    private string weather_type_short_kzField;
    
    private string weather_type_uaField;
    
    private string weather_type_short_uaField;
    
    private string weather_type_byField;
    
    private string weather_type_short_byField;
    
    private string wind_directionField;
    
    private string wind_speedField;
    
    private string humidityField;
    
    private string ipad_imageField;
    
    private station[] stationField;
    
    private temperature temperatureField;
    
    private weather_condition[] weather_conditionField;
    
    private image[] imageField;
    
    private imagev2[] imagev2Field;
    
    private imagev3[] imagev3Field;
    
    private pressure[] pressureField;
    
    private mslp_pressure[] mslp_pressureField;
    
    private season[] seasonField;
    
    private string idField;
    
    /// <remarks/>
    public string observation_time {
        get {
            return this.observation_timeField;
        }
        set {
            this.observation_timeField = value;
        }
    }
    
    /// <remarks/>
    public string uptime {
        get {
            return this.uptimeField;
        }
        set {
            this.uptimeField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type {
        get {
            return this.weather_typeField;
        }
        set {
            this.weather_typeField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_short {
        get {
            return this.weather_type_shortField;
        }
        set {
            this.weather_type_shortField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_tt {
        get {
            return this.weather_type_ttField;
        }
        set {
            this.weather_type_ttField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_short_tt {
        get {
            return this.weather_type_short_ttField;
        }
        set {
            this.weather_type_short_ttField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_tr {
        get {
            return this.weather_type_trField;
        }
        set {
            this.weather_type_trField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_short_tr {
        get {
            return this.weather_type_short_trField;
        }
        set {
            this.weather_type_short_trField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_kz {
        get {
            return this.weather_type_kzField;
        }
        set {
            this.weather_type_kzField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_short_kz {
        get {
            return this.weather_type_short_kzField;
        }
        set {
            this.weather_type_short_kzField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_ua {
        get {
            return this.weather_type_uaField;
        }
        set {
            this.weather_type_uaField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_short_ua {
        get {
            return this.weather_type_short_uaField;
        }
        set {
            this.weather_type_short_uaField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_by {
        get {
            return this.weather_type_byField;
        }
        set {
            this.weather_type_byField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_short_by {
        get {
            return this.weather_type_short_byField;
        }
        set {
            this.weather_type_short_byField = value;
        }
    }
    
    /// <remarks/>
    public string wind_direction {
        get {
            return this.wind_directionField;
        }
        set {
            this.wind_directionField = value;
        }
    }
    
    /// <remarks/>
    public string wind_speed {
        get {
            return this.wind_speedField;
        }
        set {
            this.wind_speedField = value;
        }
    }
    
    /// <remarks/>
    public string humidity {
        get {
            return this.humidityField;
        }
        set {
            this.humidityField = value;
        }
    }
    
    /// <remarks/>
    public string ipad_image {
        get {
            return this.ipad_imageField;
        }
        set {
            this.ipad_imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("station", IsNullable=true)]
    public station[] station {
        get {
            return this.stationField;
        }
        set {
            this.stationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("temperature", IsNullable=true)]
    public temperature temperature {
        get {
            return this.temperatureField;
        }
        set {
            this.temperatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("weather_condition")]
    public weather_condition[] weather_condition {
        get {
            return this.weather_conditionField;
        }
        set {
            this.weather_conditionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("image", IsNullable=true)]
    public image[] image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("image-v2", IsNullable=true)]
    public imagev2[] imagev2 {
        get {
            return this.imagev2Field;
        }
        set {
            this.imagev2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("image-v3", IsNullable=true)]
    public imagev3[] imagev3 {
        get {
            return this.imagev3Field;
        }
        set {
            this.imagev3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pressure", IsNullable=true)]
    public pressure[] pressure {
        get {
            return this.pressureField;
        }
        set {
            this.pressureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mslp_pressure", IsNullable=true)]
    public mslp_pressure[] mslp_pressure {
        get {
            return this.mslp_pressureField;
        }
        set {
            this.mslp_pressureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("season", IsNullable=true)]
    public season[] season {
        get {
            return this.seasonField;
        }
        set {
            this.seasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
public partial class forecastDay {
    
    private string sunriseField;
    
    private string sunsetField;
    
    private string moonriseField;
    
    private string moonsetField;
    
    private forecastDayMoon_phase[] moon_phaseField;
    
    private forecastDayBiomet[] biometField;
    
    private forecastDayDay_part[] day_partField;
    
    private forecastDayHour[] hourField;
    
    private string dateField;
    
    /// <remarks/>
    public string sunrise {
        get {
            return this.sunriseField;
        }
        set {
            this.sunriseField = value;
        }
    }
    
    /// <remarks/>
    public string sunset {
        get {
            return this.sunsetField;
        }
        set {
            this.sunsetField = value;
        }
    }
    
    /// <remarks/>
    public string moonrise {
        get {
            return this.moonriseField;
        }
        set {
            this.moonriseField = value;
        }
    }
    
    /// <remarks/>
    public string moonset {
        get {
            return this.moonsetField;
        }
        set {
            this.moonsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("moon_phase", IsNullable=true)]
    public forecastDayMoon_phase[] moon_phase {
        get {
            return this.moon_phaseField;
        }
        set {
            this.moon_phaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("biomet")]
    public forecastDayBiomet[] biomet {
        get {
            return this.biometField;
        }
        set {
            this.biometField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("day_part")]
    public forecastDayDay_part[] day_part {
        get {
            return this.day_partField;
        }
        set {
            this.day_partField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("hour")]
    public forecastDayHour[] hour {
        get {
            return this.hourField;
        }
        set {
            this.hourField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
public partial class forecastDayMoon_phase {
    
    private string codeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
public partial class forecastDayBiomet {
    
    private forecastDayBiometMessage[] messageField;
    
    private string indexField;
    
    private string geomagField;
    
    private string uvField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("message")]
    public forecastDayBiometMessage[] message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string geomag {
        get {
            return this.geomagField;
        }
        set {
            this.geomagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uv {
        get {
            return this.uvField;
        }
        set {
            this.uvField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
public partial class forecastDayBiometMessage {
    
    private string codeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
public partial class forecastDayDay_part {
    
    private string temperatureField;
    
    private string temperature_fromField;
    
    private string temperature_toField;
    
    private string weather_typeField;
    
    private string weather_type_shortField;
    
    private string weather_type_ttField;
    
    private string weather_type_short_ttField;
    
    private string weather_type_trField;
    
    private string weather_type_short_trField;
    
    private string weather_type_kzField;
    
    private string weather_type_short_kzField;
    
    private string weather_type_uaField;
    
    private string weather_type_short_uaField;
    
    private string weather_type_byField;
    
    private string weather_type_short_byField;
    
    private string wind_directionField;
    
    private string wind_speedField;
    
    private string humidityField;
    
    private forecastDayDay_partTemperaturedata[] temperaturedataField;
    
    private weather_condition[] weather_conditionField;
    
    private image[] imageField;
    
    private imagev2[] imagev2Field;
    
    private imagev3[] imagev3Field;
    
    private pressure[] pressureField;
    
    private mslp_pressure[] mslp_pressureField;
    
    private string typeidField;
    
    private string typeField;
    
    /// <remarks/>
    public string temperature {
        get {
            return this.temperatureField;
        }
        set {
            this.temperatureField = value;
        }
    }
    
    /// <remarks/>
    public string temperature_from {
        get {
            return this.temperature_fromField;
        }
        set {
            this.temperature_fromField = value;
        }
    }
    
    /// <remarks/>
    public string temperature_to {
        get {
            return this.temperature_toField;
        }
        set {
            this.temperature_toField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type {
        get {
            return this.weather_typeField;
        }
        set {
            this.weather_typeField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_short {
        get {
            return this.weather_type_shortField;
        }
        set {
            this.weather_type_shortField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_tt {
        get {
            return this.weather_type_ttField;
        }
        set {
            this.weather_type_ttField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_short_tt {
        get {
            return this.weather_type_short_ttField;
        }
        set {
            this.weather_type_short_ttField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_tr {
        get {
            return this.weather_type_trField;
        }
        set {
            this.weather_type_trField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_short_tr {
        get {
            return this.weather_type_short_trField;
        }
        set {
            this.weather_type_short_trField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_kz {
        get {
            return this.weather_type_kzField;
        }
        set {
            this.weather_type_kzField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_short_kz {
        get {
            return this.weather_type_short_kzField;
        }
        set {
            this.weather_type_short_kzField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_ua {
        get {
            return this.weather_type_uaField;
        }
        set {
            this.weather_type_uaField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_short_ua {
        get {
            return this.weather_type_short_uaField;
        }
        set {
            this.weather_type_short_uaField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_by {
        get {
            return this.weather_type_byField;
        }
        set {
            this.weather_type_byField = value;
        }
    }
    
    /// <remarks/>
    public string weather_type_short_by {
        get {
            return this.weather_type_short_byField;
        }
        set {
            this.weather_type_short_byField = value;
        }
    }
    
    /// <remarks/>
    public string wind_direction {
        get {
            return this.wind_directionField;
        }
        set {
            this.wind_directionField = value;
        }
    }
    
    /// <remarks/>
    public string wind_speed {
        get {
            return this.wind_speedField;
        }
        set {
            this.wind_speedField = value;
        }
    }
    
    /// <remarks/>
    public string humidity {
        get {
            return this.humidityField;
        }
        set {
            this.humidityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("temperature-data")]
    public forecastDayDay_partTemperaturedata[] temperaturedata {
        get {
            return this.temperaturedataField;
        }
        set {
            this.temperaturedataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("weather_condition")]
    public weather_condition[] weather_condition {
        get {
            return this.weather_conditionField;
        }
        set {
            this.weather_conditionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("image", IsNullable=true)]
    public image[] image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("image-v2", IsNullable=true)]
    public imagev2[] imagev2 {
        get {
            return this.imagev2Field;
        }
        set {
            this.imagev2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("image-v3", IsNullable=true)]
    public imagev3[] imagev3 {
        get {
            return this.imagev3Field;
        }
        set {
            this.imagev3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pressure", IsNullable=true)]
    public pressure[] pressure {
        get {
            return this.pressureField;
        }
        set {
            this.pressureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mslp_pressure", IsNullable=true)]
    public mslp_pressure[] mslp_pressure {
        get {
            return this.mslp_pressureField;
        }
        set {
            this.mslp_pressureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string typeid {
        get {
            return this.typeidField;
        }
        set {
            this.typeidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
public partial class forecastDayDay_partTemperaturedata {
    
    private string fromField;
    
    private string toField;
    
    private forecastDayDay_partTemperaturedataAvg[] avgField;
    
    /// <remarks/>
    public string from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    public string to {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("avg", IsNullable=true)]
    public forecastDayDay_partTemperaturedataAvg[] avg {
        get {
            return this.avgField;
        }
        set {
            this.avgField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
public partial class forecastDayDay_partTemperaturedataAvg {
    
    private string bgcolorField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bgcolor {
        get {
            return this.bgcolorField;
        }
        set {
            this.bgcolorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
public partial class forecastDayHour {
    
    private string temperatureField;
    
    private weather_condition[] weather_conditionField;
    
    private image[] imageField;
    
    private imagev2[] imagev2Field;
    
    private imagev3[] imagev3Field;
    
    private string atField;
    
    /// <remarks/>
    public string temperature {
        get {
            return this.temperatureField;
        }
        set {
            this.temperatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("weather_condition")]
    public weather_condition[] weather_condition {
        get {
            return this.weather_conditionField;
        }
        set {
            this.weather_conditionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("image", IsNullable=true)]
    public image[] image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("image-v2", IsNullable=true)]
    public imagev2[] imagev2 {
        get {
            return this.imagev2Field;
        }
        set {
            this.imagev2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("image-v3", IsNullable=true)]
    public imagev3[] imagev3 {
        get {
            return this.imagev3Field;
        }
        set {
            this.imagev3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string at {
        get {
            return this.atField;
        }
        set {
            this.atField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://weather.yandex.ru/forecast")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://weather.yandex.ru/forecast", IsNullable=false)]
public partial class NewDataSet {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("forecast", typeof(forecast))]
    [System.Xml.Serialization.XmlElementAttribute("image", typeof(image), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("image-v2", typeof(imagev2), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("image-v3", typeof(imagev3), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("mslp_pressure", typeof(mslp_pressure), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("pressure", typeof(pressure), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("season", typeof(season), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("station", typeof(station), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("temperature", typeof(temperature), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("weather_condition", typeof(weather_condition))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
