
// This file has been generated by the GUI designer. Do not modify.
namespace GtkApplication
{
	public partial class CommonVertcalStackPage
	{
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.EventBox eventbox_caption;
		
		private global::Gtk.Label label_caption;
		
		private global::Gtk.EventBox eventbox_f1_button;
		
		private global::Gtk.EventBox eventbox_f2_button;
		
		private global::Gtk.EventBox eventbox_f3_button;
		
		private global::Gtk.EventBox eventbox_f4_button;
		
		private global::Gtk.EventBox eventbox_f5_button;
		
		private global::Gtk.EventBox eventbox_f6_button;
		
		private global::Gtk.EventBox eventbox_f7_button;
		
		private global::Gtk.EventBox eventbox_f8_button;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.EventBox eventbox_exit_button;
		
		private global::Gtk.EventBox eventbox_next_button;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GtkApplication.CommonVertcalStackPage
			global::Stetic.BinContainer.Attach (this);
			this.Name = "GtkApplication.CommonVertcalStackPage";
			// Container child GtkApplication.CommonVertcalStackPage.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.vbox3.BorderWidth = ((uint)(10));
			// Container child vbox3.Gtk.Box+BoxChild
			this.eventbox_caption = new global::Gtk.EventBox ();
			this.eventbox_caption.Name = "eventbox_caption";
			// Container child eventbox_caption.Gtk.Container+ContainerChild
			this.label_caption = new global::Gtk.Label ();
			this.label_caption.Name = "label_caption";
			this.label_caption.LabelProp = global::Mono.Unix.Catalog.GetString ("Configuration");
			this.eventbox_caption.Add (this.label_caption);
			this.vbox3.Add (this.eventbox_caption);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.eventbox_caption]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.eventbox_f1_button = new global::Gtk.EventBox ();
			this.eventbox_f1_button.Name = "eventbox_f1_button";
			this.vbox3.Add (this.eventbox_f1_button);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.eventbox_f1_button]));
			w3.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.eventbox_f2_button = new global::Gtk.EventBox ();
			this.eventbox_f2_button.Name = "eventbox_f2_button";
			this.vbox3.Add (this.eventbox_f2_button);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.eventbox_f2_button]));
			w4.Position = 2;
			// Container child vbox3.Gtk.Box+BoxChild
			this.eventbox_f3_button = new global::Gtk.EventBox ();
			this.eventbox_f3_button.Name = "eventbox_f3_button";
			this.vbox3.Add (this.eventbox_f3_button);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.eventbox_f3_button]));
			w5.Position = 3;
			// Container child vbox3.Gtk.Box+BoxChild
			this.eventbox_f4_button = new global::Gtk.EventBox ();
			this.eventbox_f4_button.Name = "eventbox_f4_button";
			this.vbox3.Add (this.eventbox_f4_button);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.eventbox_f4_button]));
			w6.Position = 4;
			// Container child vbox3.Gtk.Box+BoxChild
			this.eventbox_f5_button = new global::Gtk.EventBox ();
			this.eventbox_f5_button.Name = "eventbox_f5_button";
			this.vbox3.Add (this.eventbox_f5_button);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.eventbox_f5_button]));
			w7.Position = 5;
			// Container child vbox3.Gtk.Box+BoxChild
			this.eventbox_f6_button = new global::Gtk.EventBox ();
			this.eventbox_f6_button.Name = "eventbox_f6_button";
			this.vbox3.Add (this.eventbox_f6_button);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.eventbox_f6_button]));
			w8.Position = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.eventbox_f7_button = new global::Gtk.EventBox ();
			this.eventbox_f7_button.Name = "eventbox_f7_button";
			this.vbox3.Add (this.eventbox_f7_button);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.eventbox_f7_button]));
			w9.Position = 7;
			// Container child vbox3.Gtk.Box+BoxChild
			this.eventbox_f8_button = new global::Gtk.EventBox ();
			this.eventbox_f8_button.Name = "eventbox_f8_button";
			this.vbox3.Add (this.eventbox_f8_button);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.eventbox_f8_button]));
			w10.Position = 8;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.eventbox_exit_button = new global::Gtk.EventBox ();
			this.eventbox_exit_button.Name = "eventbox_exit_button";
			this.hbox1.Add (this.eventbox_exit_button);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.eventbox_exit_button]));
			w11.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.eventbox_next_button = new global::Gtk.EventBox ();
			this.eventbox_next_button.Name = "eventbox_next_button";
			this.hbox1.Add (this.eventbox_next_button);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.eventbox_next_button]));
			w12.Position = 1;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
			w13.Position = 9;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
