
// This file has been generated by the GUI designer. Do not modify.
namespace GtkApplication
{
	public partial class OBDEngineAndFuel
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.DrawingArea d_chart;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.EventBox eventbox_primary1_max;
		
		private global::Gtk.Label label_primary1_max;
		
		private global::Gtk.ProgressBar progressbar_primary1;
		
		private global::Gtk.EventBox eventbox_primary1;
		
		private global::Gtk.Label label_primary1;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.EventBox eventbox_primary2_max;
		
		private global::Gtk.Label label_primary2_max;
		
		private global::Gtk.ProgressBar progressbar_primary2;
		
		private global::Gtk.EventBox eventbox_primary2;
		
		private global::Gtk.Label label_primary2;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.EventBox eventbox_secondary1;
		
		private global::Gtk.Label label_secondary1;
		
		private global::Gtk.EventBox eventbox_secondary2;
		
		private global::Gtk.Label label_secondary2;
		
		private global::Gtk.EventBox eventbox_secondary3;
		
		private global::Gtk.Label label_secondary3;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.EventBox eventbox_secondary4;
		
		private global::Gtk.Label label_secondary4;
		
		private global::Gtk.EventBox eventbox_secondary5;
		
		private global::Gtk.Label label_secondary5;
		
		private global::Gtk.EventBox eventbox_secondary6;
		
		private global::Gtk.Label label_secondary6;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GtkApplication.OBDEngineAndFuel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "GtkApplication.OBDEngineAndFuel";
			// Container child GtkApplication.OBDEngineAndFuel.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.d_chart = new global::Gtk.DrawingArea ();
			this.d_chart.HeightRequest = 300;
			this.d_chart.Name = "d_chart";
			this.hbox1.Add (this.d_chart);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.d_chart]));
			w1.Position = 0;
			w1.Padding = ((uint)(10));
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.eventbox_primary1_max = new global::Gtk.EventBox ();
			this.eventbox_primary1_max.Name = "eventbox_primary1_max";
			// Container child eventbox_primary1_max.Gtk.Container+ContainerChild
			this.label_primary1_max = new global::Gtk.Label ();
			this.label_primary1_max.Name = "label_primary1_max";
			this.label_primary1_max.LabelProp = global::Mono.Unix.Catalog.GetString ("label3");
			this.label_primary1_max.Justify = ((global::Gtk.Justification)(2));
			this.eventbox_primary1_max.Add (this.label_primary1_max);
			this.vbox2.Add (this.eventbox_primary1_max);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.eventbox_primary1_max]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.progressbar_primary1 = new global::Gtk.ProgressBar ();
			this.progressbar_primary1.WidthRequest = 90;
			this.progressbar_primary1.Name = "progressbar_primary1";
			this.progressbar_primary1.Orientation = ((global::Gtk.ProgressBarOrientation)(2));
			this.progressbar_primary1.Fraction = 0.44D;
			this.vbox2.Add (this.progressbar_primary1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.progressbar_primary1]));
			w4.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.eventbox_primary1 = new global::Gtk.EventBox ();
			this.eventbox_primary1.Name = "eventbox_primary1";
			// Container child eventbox_primary1.Gtk.Container+ContainerChild
			this.label_primary1 = new global::Gtk.Label ();
			this.label_primary1.Name = "label_primary1";
			this.label_primary1.LabelProp = global::Mono.Unix.Catalog.GetString ("label3");
			this.label_primary1.Justify = ((global::Gtk.Justification)(2));
			this.eventbox_primary1.Add (this.label_primary1);
			this.vbox2.Add (this.eventbox_primary1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.eventbox_primary1]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.eventbox_primary2_max = new global::Gtk.EventBox ();
			this.eventbox_primary2_max.Name = "eventbox_primary2_max";
			// Container child eventbox_primary2_max.Gtk.Container+ContainerChild
			this.label_primary2_max = new global::Gtk.Label ();
			this.label_primary2_max.Name = "label_primary2_max";
			this.label_primary2_max.LabelProp = global::Mono.Unix.Catalog.GetString ("label3");
			this.label_primary2_max.Justify = ((global::Gtk.Justification)(2));
			this.eventbox_primary2_max.Add (this.label_primary2_max);
			this.vbox3.Add (this.eventbox_primary2_max);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.eventbox_primary2_max]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.progressbar_primary2 = new global::Gtk.ProgressBar ();
			this.progressbar_primary2.WidthRequest = 90;
			this.progressbar_primary2.Name = "progressbar_primary2";
			this.progressbar_primary2.Orientation = ((global::Gtk.ProgressBarOrientation)(2));
			this.progressbar_primary2.Fraction = 0.44D;
			this.vbox3.Add (this.progressbar_primary2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.progressbar_primary2]));
			w10.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.eventbox_primary2 = new global::Gtk.EventBox ();
			this.eventbox_primary2.Name = "eventbox_primary2";
			// Container child eventbox_primary2.Gtk.Container+ContainerChild
			this.label_primary2 = new global::Gtk.Label ();
			this.label_primary2.Name = "label_primary2";
			this.label_primary2.LabelProp = global::Mono.Unix.Catalog.GetString ("label3");
			this.label_primary2.Justify = ((global::Gtk.Justification)(2));
			this.eventbox_primary2.Add (this.label_primary2);
			this.vbox3.Add (this.eventbox_primary2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.eventbox_primary2]));
			w12.PackType = ((global::Gtk.PackType)(1));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			w13.Padding = ((uint)(10));
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			w14.Padding = ((uint)(10));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Homogeneous = true;
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.eventbox_secondary1 = new global::Gtk.EventBox ();
			this.eventbox_secondary1.Name = "eventbox_secondary1";
			// Container child eventbox_secondary1.Gtk.Container+ContainerChild
			this.label_secondary1 = new global::Gtk.Label ();
			this.label_secondary1.Name = "label_secondary1";
			this.label_secondary1.Xpad = 40;
			this.label_secondary1.Ypad = 10;
			this.label_secondary1.Justify = ((global::Gtk.Justification)(2));
			this.eventbox_secondary1.Add (this.label_secondary1);
			this.hbox3.Add (this.eventbox_secondary1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.eventbox_secondary1]));
			w16.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.eventbox_secondary2 = new global::Gtk.EventBox ();
			this.eventbox_secondary2.Name = "eventbox_secondary2";
			// Container child eventbox_secondary2.Gtk.Container+ContainerChild
			this.label_secondary2 = new global::Gtk.Label ();
			this.label_secondary2.Name = "label_secondary2";
			this.label_secondary2.Xpad = 40;
			this.label_secondary2.Ypad = 10;
			this.label_secondary2.Justify = ((global::Gtk.Justification)(2));
			this.eventbox_secondary2.Add (this.label_secondary2);
			this.hbox3.Add (this.eventbox_secondary2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.eventbox_secondary2]));
			w18.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.eventbox_secondary3 = new global::Gtk.EventBox ();
			this.eventbox_secondary3.Name = "eventbox_secondary3";
			// Container child eventbox_secondary3.Gtk.Container+ContainerChild
			this.label_secondary3 = new global::Gtk.Label ();
			this.label_secondary3.Name = "label_secondary3";
			this.label_secondary3.Xpad = 40;
			this.label_secondary3.Ypad = 10;
			this.label_secondary3.Justify = ((global::Gtk.Justification)(2));
			this.eventbox_secondary3.Add (this.label_secondary3);
			this.hbox3.Add (this.eventbox_secondary3);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.eventbox_secondary3]));
			w20.Position = 2;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Homogeneous = true;
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.eventbox_secondary4 = new global::Gtk.EventBox ();
			this.eventbox_secondary4.Name = "eventbox_secondary4";
			// Container child eventbox_secondary4.Gtk.Container+ContainerChild
			this.label_secondary4 = new global::Gtk.Label ();
			this.label_secondary4.Name = "label_secondary4";
			this.label_secondary4.Xpad = 40;
			this.label_secondary4.Ypad = 10;
			this.label_secondary4.UseMarkup = true;
			this.label_secondary4.Justify = ((global::Gtk.Justification)(2));
			this.eventbox_secondary4.Add (this.label_secondary4);
			this.hbox4.Add (this.eventbox_secondary4);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.eventbox_secondary4]));
			w23.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.eventbox_secondary5 = new global::Gtk.EventBox ();
			this.eventbox_secondary5.Name = "eventbox_secondary5";
			// Container child eventbox_secondary5.Gtk.Container+ContainerChild
			this.label_secondary5 = new global::Gtk.Label ();
			this.label_secondary5.Name = "label_secondary5";
			this.label_secondary5.Xpad = 40;
			this.label_secondary5.Ypad = 10;
			this.label_secondary5.Justify = ((global::Gtk.Justification)(2));
			this.eventbox_secondary5.Add (this.label_secondary5);
			this.hbox4.Add (this.eventbox_secondary5);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.eventbox_secondary5]));
			w25.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.eventbox_secondary6 = new global::Gtk.EventBox ();
			this.eventbox_secondary6.Name = "eventbox_secondary6";
			// Container child eventbox_secondary6.Gtk.Container+ContainerChild
			this.label_secondary6 = new global::Gtk.Label ();
			this.label_secondary6.Name = "label_secondary6";
			this.label_secondary6.Xpad = 40;
			this.label_secondary6.Ypad = 10;
			this.label_secondary6.Justify = ((global::Gtk.Justification)(2));
			this.eventbox_secondary6.Add (this.label_secondary6);
			this.hbox4.Add (this.eventbox_secondary6);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.eventbox_secondary6]));
			w27.Position = 2;
			this.vbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
