
// This file has been generated by the GUI designer. Do not modify.
namespace GtkApplication
{
	public partial class ExternalApplicationPage
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Label label_launch_info;
		
		private global::Gtk.ToggleButton button_close;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GtkApplication.ExternalApplicationPage
			global::Stetic.BinContainer.Attach (this);
			this.Name = "GtkApplication.ExternalApplicationPage";
			// Container child GtkApplication.ExternalApplicationPage.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label_launch_info = new global::Gtk.Label ();
			this.label_launch_info.Name = "label_launch_info";
			this.label_launch_info.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.vbox1.Add (this.label_launch_info);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label_launch_info]));
			w1.Position = 1;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(20));
			// Container child vbox1.Gtk.Box+BoxChild
			this.button_close = new global::Gtk.ToggleButton ();
			this.button_close.CanFocus = true;
			this.button_close.Name = "button_close";
			this.button_close.UseUnderline = true;
			this.button_close.Label = global::Mono.Unix.Catalog.GetString ("GtkToggleButton");
			this.vbox1.Add (this.button_close);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.button_close]));
			w2.Position = 2;
			w2.Expand = false;
			w2.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
