
// This file has been generated by the GUI designer. Do not modify.
namespace GtkApplication
{
	public partial class CircularGauge
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget GtkApplication.CircularGauge
			global::Stetic.BinContainer.Attach(this);
			this.Name = "GtkApplication.CircularGauge";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
