
// This file has been generated by the GUI designer. Do not modify.
namespace GtkApplication
{
	public partial class FileOptionsPage
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.EventBox eventbox_file_name;
		
		private global::Gtk.Label label_file_name;
		
		private global::Gtk.EventBox eventbox_file_props;
		
		private global::Gtk.Label label_file_props;
		
		private global::Gtk.EventBox eventbox_f1;
		
		private global::Gtk.EventBox eventbox_f2;
		
		private global::Gtk.EventBox eventbox_f3;
		
		private global::Gtk.EventBox eventbox_f4;
		
		private global::Gtk.EventBox eventbox_f5;
		
		private global::Gtk.EventBox eventbox_cancel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GtkApplication.FileOptionsPage
			global::Stetic.BinContainer.Attach (this);
			this.Name = "GtkApplication.FileOptionsPage";
			// Container child GtkApplication.FileOptionsPage.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.eventbox_file_name = new global::Gtk.EventBox ();
			this.eventbox_file_name.Name = "eventbox_file_name";
			// Container child eventbox_file_name.Gtk.Container+ContainerChild
			this.label_file_name = new global::Gtk.Label ();
			this.label_file_name.Name = "label_file_name";
			this.label_file_name.LabelProp = global::Mono.Unix.Catalog.GetString ("<span size=\'20000\'>1.h264</span>");
			this.label_file_name.UseMarkup = true;
			this.eventbox_file_name.Add (this.label_file_name);
			this.vbox1.Add (this.eventbox_file_name);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.eventbox_file_name]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.eventbox_file_props = new global::Gtk.EventBox ();
			this.eventbox_file_props.Name = "eventbox_file_props";
			// Container child eventbox_file_props.Gtk.Container+ContainerChild
			this.label_file_props = new global::Gtk.Label ();
			this.label_file_props.Name = "label_file_props";
			this.label_file_props.LabelProp = global::Mono.Unix.Catalog.GetString ("<span size=\'14000\'>Created: 22-feb-2016 (76 Mb)</span>");
			this.label_file_props.UseMarkup = true;
			this.eventbox_file_props.Add (this.label_file_props);
			this.vbox1.Add (this.eventbox_file_props);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.eventbox_file_props]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.eventbox_f1 = new global::Gtk.EventBox ();
			this.eventbox_f1.Name = "eventbox_f1";
			this.vbox1.Add (this.eventbox_f1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.eventbox_f1]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Padding = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.eventbox_f2 = new global::Gtk.EventBox ();
			this.eventbox_f2.Name = "eventbox_f2";
			this.vbox1.Add (this.eventbox_f2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.eventbox_f2]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Padding = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.eventbox_f3 = new global::Gtk.EventBox ();
			this.eventbox_f3.Name = "eventbox_f3";
			this.vbox1.Add (this.eventbox_f3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.eventbox_f3]));
			w7.Position = 4;
			w7.Expand = false;
			w7.Padding = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.eventbox_f4 = new global::Gtk.EventBox ();
			this.eventbox_f4.Name = "eventbox_f4";
			this.vbox1.Add (this.eventbox_f4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.eventbox_f4]));
			w8.Position = 5;
			w8.Expand = false;
			w8.Padding = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.eventbox_f5 = new global::Gtk.EventBox ();
			this.eventbox_f5.Name = "eventbox_f5";
			this.vbox1.Add (this.eventbox_f5);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.eventbox_f5]));
			w9.Position = 6;
			w9.Expand = false;
			w9.Padding = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.eventbox_cancel = new global::Gtk.EventBox ();
			this.eventbox_cancel.Name = "eventbox_cancel";
			this.vbox1.Add (this.eventbox_cancel);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.eventbox_cancel]));
			w10.PackType = ((global::Gtk.PackType)(1));
			w10.Position = 8;
			w10.Expand = false;
			w10.Padding = ((uint)(5));
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
