
// This file has been generated by the GUI designer. Do not modify.
namespace GtkApplication
{
	public partial class DrivePage
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.HSeparator hseparator2;

		private global::Gtk.Label label_last_message;

		private global::Gtk.HBox hbox4;

		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Image image_weather_icon;

		private global::Gtk.Label label_air_temp;

		private global::Gtk.HBox hbox3;

		private global::Gtk.HSeparator hseparator3;

		private global::Gtk.Label label_heading;

		private global::Gtk.Image image_map;

		private global::Gtk.Table table1;

		private global::Gtk.Label label_cpu_info;

		private global::Gtk.Label label_exported_points;

		private global::Gtk.Label label_lat;

		private global::Gtk.Label label_lon;

		private global::Gtk.HSeparator hseparator4;

		private global::Gtk.Image image1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label_speed;

		private global::Gtk.Image image2;

		private global::Gtk.Label label_travel_span;

		private global::Gtk.Label label_distance;

		private global::Gtk.Image image3;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Image image_oil_temp;

		private global::Gtk.EventBox eventbox_eng_temp;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.HBox hbox5;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget GtkApplication.DrivePage
			global::Stetic.BinContainer.Attach(this);
			this.WidthRequest = 800;
			this.HeightRequest = 480;
			this.Name = "GtkApplication.DrivePage";
			// Container child GtkApplication.DrivePage.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.HeightRequest = 35;
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			this.hbox1.BorderWidth = ((uint)(5));
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w1.Position = 0;
			w1.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator();
			this.hseparator2.Name = "hseparator2";
			this.vbox1.Add(this.hseparator2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator2]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label_last_message = new global::Gtk.Label();
			this.label_last_message.HeightRequest = 54;
			this.label_last_message.Name = "label_last_message";
			this.label_last_message.LabelProp = global::Mono.Unix.Catalog.GetString("No message");
			this.label_last_message.UseMarkup = true;
			this.vbox1.Add(this.label_last_message);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label_last_message]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.WidthRequest = 250;
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.vbox3.BorderWidth = ((uint)(20));
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.image_weather_icon = new global::Gtk.Image();
			this.image_weather_icon.Name = "image_weather_icon";
			this.hbox6.Add(this.image_weather_icon);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.image_weather_icon]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(20));
			// Container child hbox6.Gtk.Box+BoxChild
			this.label_air_temp = new global::Gtk.Label();
			this.label_air_temp.Name = "label_air_temp";
			this.label_air_temp.Yalign = 0.73F;
			this.label_air_temp.LabelProp = "<span foreground=\'#d6d6d6\' size=\'14000\'>Air temp: </span><span foreground=\'#d6d6d" +
				"6\' size=\'20000\'>--</span>";
			this.label_air_temp.UseMarkup = true;
			this.label_air_temp.Wrap = true;
			this.hbox6.Add(this.label_air_temp);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label_air_temp]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox3.Add(this.hbox6);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox6]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator();
			this.hseparator3.WidthRequest = 80;
			this.hseparator3.Name = "hseparator3";
			this.hbox3.Add(this.hseparator3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hseparator3]));
			w7.Position = 1;
			w7.Fill = false;
			this.vbox3.Add(this.hbox3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label_heading = new global::Gtk.Label();
			this.label_heading.Name = "label_heading";
			this.label_heading.Yalign = 0.73F;
			this.label_heading.LabelProp = "<span foreground=\'#d6d6d6\' size=\'14000\'>Heading: </span><span foreground=\'#d6d6d6" +
				"\' size=\'20000\'>--</span>";
			this.label_heading.UseMarkup = true;
			this.label_heading.Wrap = true;
			this.label_heading.Justify = ((global::Gtk.Justification)(2));
			this.vbox3.Add(this.label_heading);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label_heading]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.image_map = new global::Gtk.Image();
			this.image_map.Name = "image_map";
			this.vbox3.Add(this.image_map);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.image_map]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), true);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(50));
			// Container child table1.Gtk.Table+TableChild
			this.label_cpu_info = new global::Gtk.Label();
			this.label_cpu_info.Name = "label_cpu_info";
			this.label_cpu_info.Xalign = 0.1F;
			this.label_cpu_info.Yalign = 0.73F;
			this.label_cpu_info.LabelProp = "<span foreground=\'#d6d6d6\' size=\'14000\'></span>";
			this.label_cpu_info.UseMarkup = true;
			this.table1.Add(this.label_cpu_info);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.label_cpu_info]));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label_exported_points = new global::Gtk.Label();
			this.label_exported_points.Name = "label_exported_points";
			this.label_exported_points.Xalign = 0.1F;
			this.label_exported_points.Yalign = 0.73F;
			this.label_exported_points.LabelProp = "<span foreground=\'#d6d6d6\' size=\'14000\'>Lon: --</span>";
			this.label_exported_points.UseMarkup = true;
			this.table1.Add(this.label_exported_points);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.label_exported_points]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label_lat = new global::Gtk.Label();
			this.label_lat.Name = "label_lat";
			this.label_lat.Xalign = 0.1F;
			this.label_lat.Yalign = 0.73F;
			this.label_lat.LabelProp = "<span foreground=\'#d6d6d6\' size=\'14000\'>Lat: --</span>";
			this.label_lat.UseMarkup = true;
			this.table1.Add(this.label_lat);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.label_lat]));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label_lon = new global::Gtk.Label();
			this.label_lon.Name = "label_lon";
			this.label_lon.Xalign = 0.1F;
			this.label_lon.Yalign = 0.73F;
			this.label_lon.LabelProp = "<span foreground=\'#d6d6d6\' size=\'14000\'>Lon: --</span>";
			this.label_lon.UseMarkup = true;
			this.table1.Add(this.label_lon);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.label_lon]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add(this.table1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.table1]));
			w15.PackType = ((global::Gtk.PackType)(1));
			w15.Position = 4;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator4 = new global::Gtk.HSeparator();
			this.hseparator4.WidthRequest = 50;
			this.hseparator4.Name = "hseparator4";
			this.vbox3.Add(this.hseparator4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hseparator4]));
			w16.PackType = ((global::Gtk.PackType)(1));
			w16.Position = 5;
			w16.Expand = false;
			w16.Fill = false;
			this.hbox4.Add(this.vbox3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox3]));
			w17.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image();
			this.image1.Name = "image1";
			this.hbox4.Add(this.image1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.image1]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.WidthRequest = 389;
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label_speed = new global::Gtk.Label();
			this.label_speed.HeightRequest = 250;
			this.label_speed.Name = "label_speed";
			this.label_speed.Yalign = 1F;
			this.label_speed.LabelProp = "<span foreground=\'#FFFFFF\' size=\'90000\'><b>-</b></span>";
			this.label_speed.UseMarkup = true;
			this.label_speed.Justify = ((global::Gtk.Justification)(2));
			this.vbox2.Add(this.label_speed);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label_speed]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.image2 = new global::Gtk.Image();
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("GtkApplication.Resources.Sep_kmh.png");
			this.vbox2.Add(this.image2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.image2]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label_travel_span = new global::Gtk.Label();
			this.label_travel_span.HeightRequest = 50;
			this.label_travel_span.Name = "label_travel_span";
			this.label_travel_span.Yalign = 1F;
			this.label_travel_span.LabelProp = "<span foreground=\'#D6D6D6\' size=\'20000\'>0 min</span>";
			this.label_travel_span.UseMarkup = true;
			this.vbox2.Add(this.label_travel_span);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label_travel_span]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label_distance = new global::Gtk.Label();
			this.label_distance.HeightRequest = 50;
			this.label_distance.Name = "label_distance";
			this.label_distance.Yalign = 1F;
			this.label_distance.LabelProp = "<span foreground=\'#AAAAAA\' size=\'20000\'>0 km</span>";
			this.label_distance.UseMarkup = true;
			this.vbox2.Add(this.label_distance);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label_distance]));
			w22.Position = 3;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.image3 = new global::Gtk.Image();
			this.image3.Name = "image3";
			this.image3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("GtkApplication.Resources.Sep_route.png");
			this.vbox2.Add(this.image3);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.image3]));
			w23.Position = 4;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Homogeneous = true;
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.image_oil_temp = new global::Gtk.Image();
			this.image_oil_temp.WidthRequest = 32;
			this.image_oil_temp.Name = "image_oil_temp";
			this.image_oil_temp.Xalign = 1F;
			this.hbox2.Add(this.image_oil_temp);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.image_oil_temp]));
			w24.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.eventbox_eng_temp = new global::Gtk.EventBox();
			this.eventbox_eng_temp.HeightRequest = 150;
			this.eventbox_eng_temp.Name = "eventbox_eng_temp";
			this.hbox2.Add(this.eventbox_eng_temp);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.eventbox_eng_temp]));
			w25.Position = 1;
			w25.Expand = false;
			this.vbox2.Add(this.hbox2);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
			w26.Position = 5;
			w26.Expand = false;
			w26.Fill = false;
			this.hbox4.Add(this.vbox2);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox2]));
			w27.PackType = ((global::Gtk.PackType)(1));
			w27.Position = 2;
			w27.Fill = false;
			this.vbox1.Add(this.hbox4);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
			w28.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator1]));
			w29.Position = 4;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.HeightRequest = 60;
			this.hbox5.Name = "hbox5";
			this.hbox5.Homogeneous = true;
			this.hbox5.Spacing = 6;
			this.vbox1.Add(this.hbox5);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
			w30.PackType = ((global::Gtk.PackType)(1));
			w30.Position = 5;
			w30.Expand = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
